spring.datasource:
  url: jdbc:postgresql://localhost:5432/bookstore
  username: postgres
  password: percia123
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true